### ISSUE TITLE
sklearn models

### ISSUE THREAD

**Issue by emphasize** [OpenVoiceOS/ovos-classifiers#2]
I have doubts on the way sklearn models were trained. The only "feature" is the word itself, devoid of any contextual specification.

I've seen additional features extracted [here](https://nlpforhackers.io/training-pos-tagger/)

Features, i.e. X[n]
``` features of "a" in the sentence ['This', 'is', 'a', 'sentence']
{'capitals_inside': False,
 'has_hyphen': False,
 'is_all_caps': False,
 'is_all_lower': True,
 'is_capitalized': False,
 'is_first': False,
 'is_last': False,
 'is_numeric': False,
 'next_word': 'sentence',
 'prefix-1': 'a',
 'prefix-2': 'a',
 'prefix-3': 'a',
 'prev_word': 'is',
 'suffix-1': 'a',
 'suffix-2': 'a',
 'suffix-3': 'a',
 'word': 'a'}
 ```
 
 ```python
 def features(sentence, index):
    """ sentence: [w1, w2, ...], index: the index of the word """
    return {
        'word': sentence[index],
        'is_first': index == 0,
        'is_last': index == len(sentence) - 1,
        'is_capitalized': sentence[index][0].upper() == sentence[index][0],
        'is_all_caps': sentence[index].upper() == sentence[index],
        'is_all_lower': sentence[index].lower() == sentence[index],
        'prefix-1': sentence[index][0],
        'prefix-2': sentence[index][:2],
        'prefix-3': sentence[index][:3],
        'suffix-1': sentence[index][-1],
        'suffix-2': sentence[index][-2:],
        'suffix-3': sentence[index][-3:],
        'prev_word': '' if index == 0 else sentence[index - 1],
        'next_word': '' if index == len(sentence) - 1 else sentence[index + 1],
        'has_hyphen': '-' in sentence[index],
        'is_numeric': sentence[index].isdigit(),
        'capitals_inside': sentence[index][1:].lower() != sentence[index][1:]
    }
```

The lack of context and the minimal train data size should make those models perform poorly in production

**Comment by JarbasAl** [comment]
What task are you talking about? Features need a context to make sense, more features is not necessarily good. But in general note this repo is very very early and does not reflect best practices all the time, I am benchmarking different models and some will purposefully not use best features or algorithms, prs always welcome to train new sets of models with different params so they can be benchmarked against others.

**Comment by emphasize** [comment]
That is done in all sklearn training scripts (for instance using [this method](https://github.com/OpenVoiceOS/ovos-classifiers/blob/a9d20c4b83da8140be32d240931f1ebffd22badf/ovos_classifiers/datasets/__init__.py#L11))

```python
def _tagged_to_dataset(tagged_sentences):
    X, y = [], []

    for tagged in tagged_sentences:
        for index in range(len(tagged)):
            X.append(tagged[index][0])           #  here the different features should be added
            y.append(tagged[index][1])

    return X, y
```

The way it is now, it is only trained word -> pos,  and based on the train data pos is fixed on that word, without taking other features into concidderation.

**Comment by JarbasAl** [comment]
that is handling the dataset loading only, the feature are extracted afterwards

feature handling comes from the vectorizers and will depend on the pipeline object selected during training

see https://github.com/OpenVoiceOS/ovos-classifiers/blob/dev/ovos_classifiers/skovos/pipelines.py#L87

**Comment by emphasize** [comment]
How do you figure that? After flatten the tagged sentences there is no _contextual_  information to extract (ie. the word relative to other words in a sentence)

**Comment by JarbasAl** [comment]
that is loading the dataset, that code is dataset specific

the features are extracted via pipeline, eg, https://github.com/OpenVoiceOS/ovos-classifiers/blob/dev/ovos_classifiers/skovos/tagger.py#L6 -> https://github.com/OpenVoiceOS/ovos-classifiers/blob/4023416c374bce2a6807be83bfbea3df8ec822db/ovos_classifiers/skovos/features/__init__.py#L74

in the case of the default "naive" pipeline

```
   def transform(self, X, **transform_params):
        feats = [
            extract_word_features(X, index, stemmer=self.stemmer,
                                  memory=self.memory)
            for index in range(len(X))]
```

as you can see for each word the features do include context


the features are not part of data loading, they are part of the model since the same features need to be extracted at inference time, the pipeline abstraction from scikit learn makes this a breeze to work with via the transformer/vectorizer classes

**Comment by emphasize** [comment]
Thanks for the details
